### ISSUE TITLE
Auto pagination with prefix transformation - "Cannot return null for non-nullable field Query.<field_name>"

### ISSUE THREAD

**Issue by OlaStenberg** [graphprotocol/graph-client#102]
I have two sources with prefixes and can't get auto pagination to work, when I run this query: https://codesandbox.io/s/sharp-faraday-3drfno?file=/kovan-legacy-exchange.graphql
(`first: 1000` works)

Error message:
![image](https://user-images.githubusercontent.com/29061789/169140559-cb9f92dd-4a49-465c-b6ea-a47541428488.png)

**Comment by dotansimha** [comment]
@ardatan what do you think?

**Comment by ardatan** [comment]
@OlaStenberg Could you test with these versions?
https://github.com/graphprotocol/graph-client/pull/110#issuecomment-1148792629

**Comment by dotansimha** [comment]
Fixed in: 
```
@graphprotocol/client-cli@2.0.1
@graphprotocol/client-block-tracking@1.0.2
@graphprotocol/client-auto-pagination@1.0.2
```
