### ISSUE TITLE
Use graph client with docker network based graph node

### ISSUE THREAD

**Issue by rhlsthrm** [graphprotocol/graph-client#132]
We are using a graph node as part of a fully-local setup:

https://github.com/connext/nxtp/blob/a0eb052ac0abb8b83821005f1c44dd8d2448a1fb/docker-compose.chains.yaml#L21

I want to be able to generate a graph client that can be used on resources within this docker network that talk to the graph node. The config for this would look like this:

https://github.com/connext/nxtp/blob/e0519f79172025770047e3aed5c7fa5796f6d56c/packages/adapters/subgraph/.graphclientrc.yml#L140

However I am not able to easily generate the client for this. When I try, it fails because the host cannot access this endpoint. If I use localhost, the container cannot access the graph node because it's not on localhost from the container's point of view. The workaround I used is to spin up a temporary container within the network that can do this. However this is not a feasible option for our devs to use.

Is there another way to generate the schema from a different URL but have the client use the provided URL for the queries?

**Comment by ardatan** [comment]
You can use string interpolation to give different values for `endpoint`;
```yml
endpoint: "{env.MY_ENDPOINT}"
```
So you will give different env var during the build, and use a different one in the docker container.

**Comment by rhlsthrm** [comment]
@ardatan this is perfect, thank you for this!

**Comment by base0010** [comment]
> You can use string interpolation to give different values for `endpoint`;
> 
> ```yaml
> endpoint: "{env.MY_ENDPOINT}"
> ```
> 
> So you will give different env var during the build, and use a different one in the docker container.

Tried this as mentioned and seemed to work fine for the generation step however at runtime we get this error,
`💥 🕸️  Mesh TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/home/node/node_modules/node-fetch/lib/index.js:1327:9)
   ....` is there another option or parameter we need to enable to get this to work @ardatan

**Comment by ardatan** [comment]
What do you provide in your env variable?

**Comment by stefan-girlich** [comment]
perfect, both options work for me and could be a valuable addition to the docs.

related question: in `.graphclientrc.yml`, i want to create 1-n `sources` entries programmatically, also using env vars. is there a syntactic construct which allows that? if not, i would simply create the entire file `.graphclientrc.yml` programmatically.

thanks so much for the quick answer, i highly appreciated it 💯
