### ISSUE TITLE
Order by nested relation

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#145]
```graphql
a (orderBy: b.value) {
  b {
    value
  }
}
```

I assume this is limitation with GraphQL, and/or implementation of it by The Graph, since I'm unable to do a simple orderBy: b.value

Have any suggestions here? I wonder if we can work around this with graph client since not being able to order by a property nested 1 level deep seems silly...

Sorry to tag but I'm sure you work some magic @ardatan

**Comment by dotansimha** [comment]
At the moment you can only override the resolver and implement your own login to filter by that entity. 
We recently got this PR merged in `graph-node`: https://github.com/graphprotocol/graph-node/pull/3184 (it's currently in testing, we expect this to be available to use very soon!)

**Comment by matthewlilley** [comment]
> resolver

Amazing! Thanks for the heads up on this one.

**Comment by matthewlilley** [comment]
> > resolver
> 
>

**Comment by matthewlilley** [comment]
> At the moment you can only override the resolver and implement your own login to filter by the entities: https://www.graphql-mesh.com/docs/guides/extending-unified-schema#programatic-additionalresolvers
> 
> We recently got this PR merged in `graph-node`: [graphprotocol/graph-node#3184](https://github.com/graphprotocol/graph-node/pull/3184) (it's currently in testing, we expect this to be available to use very soon! this is a part of a bigger work we are doing to improve the GraphQL schema provided by The Graph)

Amazing! Thanks for the heads up on this one.
