### ISSUE TITLE
Custom resolver in cross chain mode fail if one source fails

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#146]
Using the cross-chain-extensions example which has been very useful, but If I have 20 sources for the same subgraph across networks and I'm querying them as a whole, if one endpoint fails, it seems the entire thing fails. 

I wonder if there's a way to make this more robust in the sense that it can deal with some of the endpoints failing but still return data for the others, or else the weakest link will always be a problem in cross chain mode.

**Comment by ardatan** [comment]
`Promise.allSettled` can be used instead of `Promise.all` maybe?

**Comment by ardatan** [comment]
Does this solve your issue? If yes, would you create a PR to update the example on the repo? Thanks!

**Comment by ardatan** [comment]
Closing this issue for now then. We can reopen it later if it still doesn't work
