### ISSUE TITLE
Unexpected behavior from first & where

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#148]
const { liquidityPositions }: { liquidityPositions: LiquidityPosition[] } = await sdk.LiquidityPositions({
    first: 1000,
    where: { user: MAKER_ADDRESS[chainId] },
})

You would think this would be "WHERE user = MAKER_ADDRESS" return first 1000 enitites where this condition is met. 

However, The GraphQL implementation by The Graph does not work in this way, it is scanning the first 1000 rows, and returning entities where that condition is met. This is very confusing behavior.... And means that for the above usage, first would have to be the total number of LiquidityPosition's ever known in the system, regardless of user.

**Comment by matthewlilley** [comment]
Unfortunately, this makes auto pagination pretty much useless. I think there has been an implementation error in the creation of auto pagination, maybe because this behavior is odd. You cannot use first/skip as a limit/offset. It just doesn't work in a performant way with The Graph.

**Comment by ardatan** [comment]
@dotansimha I'm not sure how we can solve this on the client side. Any ideas?

**Comment by matthewlilley** [comment]
@ardatan this is a bit of a tricky one. The alternative is querying this way around but first > 1000 does nothing.

https://github.com/graphprotocol/graph-client/issues/149

**Comment by ardatan** [comment]
@matthewlilley I think this is an unexpected behavior of `graph-node` and I don't think this is something needs to be fixed on Graph Node itself.

**Comment by matthewlilley** [comment]
@ardatan Yes, it's unusual behavior of The Graph node. Sometimes we do need to get all records for a particular reason though, in our previous pager we used this method to speed it up.

https://thegraph.com/docs/en/querying/graphql-api/#example-using-and-2

**Comment by ardatan** [comment]
@dotansimha @kamilkisiela  Should we move this issue to graph-node?

**Comment by dotansimha** [comment]
> @dotansimha @kamilkisiela Should we move this issue to graph-node?

I'm working on a reproduction and then will open an issue with all the details. Thanks!

**Comment by dotansimha** [comment]
Hi @matthewlilley , I tested ~10 subgraphs with different setups ,but this does not reproduce at all. Can you please share a Subgraph + a query that produces invalid data based on pagination + where filter?

**Comment by matthewlilley** [comment]
@dotansimha I've asked Lufy to make a repro. We can reproduce this quite easily in a lot of different cases. Will post shortly.

**Comment by dotansimha** [comment]
> @dotansimha I've asked Lufy to make a repro. We can reproduce this quite easily in a lot of different cases. Will post shortly.

Thanks! Please keep us updated :) Keeping open

**Comment by azf20** [comment]
Hey @matthewlilley I think this is expected behaviour, filtering on ID is applied before the orderBy - you need to filter by the field you are ordering by. This is a slight issue with current Graph Node pagination if the orderBy is not distinct. There is work in progress to support cursor-based pagination https://github.com/graphprotocol/graph-node/pull/3214 (this is an older PR, there is more recent work here)
