### ISSUE TITLE
Single source will cause generate to fail, adding second will allow it to succeed

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#150]
In the past few days a bug was introduced, I think by the core graph mesh libraries, which now causes generation to fail if you have a single source.

**Comment by ardatan** [comment]
Could you share a reproduction on CodeSandbox or StackBlitz? Thanks!

**Comment by matthewlilley** [comment]
If you're able to generate with a single source then I'd assume it's resolved here, we're using multiple sources in all ours at the moment, this was happening in the blog which I moved over to regular graph mesh since it wasn't using any subgraphs.

**Comment by ardatan** [comment]
Seems fine. We can close it :)
