### ISSUE TITLE
Built-in implementation for client-side mutations? 

### ISSUE THREAD

**Issue by dotansimha** [graphprotocol/graph-client#16]
Inspiration: https://github.com/graphprotocol/mutations

**Comment by dotansimha** [comment]
@ardatan @azf20 what do you think? 
We can integrate this tool with the client, so you can define the mutations as part of the composed schema (today, dapps need to separate schema for that)

**Comment by azf20** [comment]
Hey @dotansimha interesting - graphprotocol/mutations hasn't been actively maintained for a while, would that be the best tool to use here?

**Comment by dotansimha** [comment]
> Hey @dotansimha interesting - graphprotocol/mutations hasn't been actively maintained for a while, would that be the best tool to use here?

I think we can integrate that as `additionalTypedefs` that already exist in Mesh. Also, it will be fully typed and decoupled from the app state (the `graphprotocol/mutations` is super specific to apollo, and it created a new local schema). 
Doing it with Mesh will create a single composed schema with any custom schema/code, so it should make it easier.

**Comment by azf20** [comment]
OK - so goal is to use Mesh instead of `graphprotocol/mutations`?

**Comment by dotansimha** [comment]
> OK - so goal is to use Mesh instead of `graphprotocol/mutations`?

Yeah, I think so, this way dApps can implement custom logic and choose how to manage and execute mutations (for example: log in with wallet, sign a message, the send it directly to the smart contract).

**Comment by azf20** [comment]
OK - that sounds good to me. Feels like we could have some nice illustrative examples, in particular of how it can tidy up frontend code!
