### ISSUE TITLE
Improve and update documentation and examples 

### ISSUE THREAD

**Issue by dotansimha** [graphprotocol/graph-client#177]
Also, move the major part of the docs to https://github.com/graphprotocol/docs 

## TODO 
- [x] https://github.com/graphprotocol/docs/pull/183/files#diff-eb3f534cddd1e9353423a2efa6d73b602c6ed681c7f7bf5162733655526c4862R28
- [ ] More examples and document the enabled by default plugins

**Comment by charlypoly** [comment]
@dotansimha, I've already update The Graph docs to better showcase `graph-client`: https://github.com/graphprotocol/docs/pull/183/files#diff-eb3f534cddd1e9353423a2efa6d73b602c6ed681c7f7bf5162733655526c4862R28

Is it sufficient or would you like to see more usage/configuration details?

**Comment by dotansimha** [comment]
Yeah, that's perfect for now. I do want to move some usage and examples for specific features, but we want to make some features enabled and included by default (like `@live`).
