### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by OlaStenberg** [graphprotocol/graph-client#189]
Would it be possible to improve this error message:
![image](https://user-images.githubusercontent.com/29061789/184076656-0a1d68e1-5920-4e5b-ad9a-b1aefc02ca55.png)

This shows when there's something wrong in the `query.graphql` file, I've seen it multiple times when the schema has changed and query still has an old field..

**Comment by dotansimha** [comment]
@ardatan can you please take a look?

**Comment by OlaStenberg** [comment]
> @ardatan can you please take a look? @OlaStenberg can you please share a reproduction and/or graphclient config file?

https://codesandbox.io/s/kind-parm-b4j429?file=/example-query.graphql

![image](https://user-images.githubusercontent.com/29061789/185925316-1ff17a4d-e8c0-451d-b52c-0aa54e0dfe39.png)

**Comment by ardatan** [comment]
This issue has been fixed in the latest release but currently you can see the entire error message if `DEBUG=1` env var exists, I am working on this PR in order to show the entire stack trace even if `DEBUG` doesn't exist.
Could you confirm? Thanks.

**Comment by OlaStenberg** [comment]
Without DEBUG=1
![image](https://user-images.githubusercontent.com/29061789/186138769-b20da227-8a0f-4e36-9b71-622ccd035824.png)

With DEBUG=1
![image](https://user-images.githubusercontent.com/29061789/186139034-e8740596-444f-437c-825a-0631f819a6fe.png)

Thanks, that's better, not sure why it's complaining about id though

**Comment by OlaStenberg** [comment]
lol yup, sorry

![image](https://user-images.githubusercontent.com/29061789/186173611-3cc89dad-dfcc-4d73-816e-c806d23cf613.png)

Looks good, thanks!
