### ISSUE TITLE
Next.js example

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#19]
Thanks for sharing these. I've tried using various of the examples provided in a Next.js application, I was hoping to use Apollo but failed to get it running smoothly. It would be useful to see some examples if you have the time to do that :)

**Comment by matthewlilley** [comment]
I think the issues I was seeing was when using Apollo, and more complex config with transforms. I tried again this morning and I was able to get data with the simple version, but lots of critical errors in console the moment I make it slightly more complex.

**Comment by ardatan** [comment]
@matthewlilley Could you share your example that has those errors?

**Comment by matthewlilley** [comment]
For context, we have around 15 identical subgraphs across different networks for our exchange. I'd like to query them all in one, with at least some simple transformations like prefixing ETHEREUM_, MATIC_, etc... and later would like to apply some schema stitching too. The basic example works great, but since they're the same I need transforms. I'd also like to use Apollo on the frontend so I can continue to get fresh data after the initial hydration from the server.

**Comment by matthewlilley** [comment]
> 

Yeah, sure. Let me throw it up.

**Comment by matthewlilley** [comment]
> @matthewlilley Could you share your example that has those errors?

Yeah, sure. Let me throw it up.

**Comment by matthewlilley** [comment]
You'll want to pull this branch

https://github.com/sushiswap/interface/tree/feature/analytics

- pnpm i
- pnpx turbo run dev
- pnpx turbo run dev --scope=analytics

This isn't using Apollo at the moment, and I get the data, but see a lot of these critical dependency warnings in console.

I'll try wiring up Apollo in the meantime, I never managed to get this working with any kind of transforms, I expect the simple version will work fine.

**Comment by matthewlilley** [comment]
![image](https://user-images.githubusercontent.com/6063350/161090913-33c5a18e-0d84-4c0f-ac24-e8ad56745bba.png)

Even though this was working in development with the errors, I'm seeing this when building in production.

**Comment by matthewlilley** [comment]
Turns out this build error is because Node 16 is required and Vercel only supports Node 14.

**Comment by matthewlilley** [comment]
#34

**Comment by matthewlilley** [comment]
It would be good to see a Next.js example with Apollo & urlq, right now both fail with the common errors you see with isomorphic web frameworks, e.g. "Module not found: Can't resolve 'fs'".

**Comment by matthewlilley** [comment]
Seems to always be issues like this when the generated library is imported on the client. I've only been able to make use on the server so far. I've never had a problem with Apollo in Next.js before so assume this is a graphprotocol/client or graphqlmesh issue.

**Comment by ardatan** [comment]
It is not this project specifically but GraphQL Mesh which Graph Client heavily uses under the hood. We deployed one of our example projects that use GraphQL Handler just like GraphQL Client to Vercel;

Logs; https://vercel.com/theguild/graphql-mesh/A3MASwMEGhpWbwj4scpPy6t1bhqj
Working endpoint; https://graphql-mesh.com/api/covid
Project; https://github.com/Urigo/graphql-mesh/tree/master/website/src/pages/api/covid

**Comment by dotansimha** [comment]
Hi there! With the recent upgrades in `graph-client` internals, we can see that running it in NextJS works fine :) 
Please try `@graphprotocol/client-cli@0.0.5` and let me know if we need to reopen this issue. Also we updated the examples here: https://github.com/graphprotocol/graph-client/tree/main/examples/nextjs

**Comment by dotansimha** [comment]
Fixed in: 

```
@graphprotocol/client-apollo@0.0.4
@graphprotocol/client-cli@0.0.6
@graphprotocol/client-urql@0.0.4
```

PR: https://github.com/graphprotocol/graph-client/pull/50
release notes: https://github.com/graphprotocol/graph-client/pull/51

**Comment by ivanminutillo** [comment]
fyi latest release 3.0.3 has same issue, downgrading to 3.0.1 fixes it

**Comment by ardatan** [comment]
Could you create a new issue with a reproduction?
