### ISSUE TITLE
AggregateError

### ISSUE THREAD

**Issue by GundamDweeb** [graphprotocol/graph-client#209]
GM

I was going fine incorporating a GraphQL document into my next project.

I encountered this error when I tried to add a second GraphQL document, and still encounter it after:
- Reverting changes
- Clearing .graphclient, node_modules and reinstalling & building
- Creating a new branch from main with the original working branch

#### Error

```
yarn run v1.22.19
$ graphclient build
💡 GraphClient Cleaning existing artifacts
💡 GraphClient Reading the configuration
💡 GraphClient Generating the unified schema
💡 GraphClient Generating artifacts
💡 GraphClient Generating index file in TypeScript
💥 GraphClient AggregateError: GraphQL Document Validation failed with 1 errors;
  Error 0: GraphQLDocumentError: V...
error Command failed with exit code 1.
```

#### Client Manifest

```
sources:
  - name: InsertName
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/InsertName/InsertName-mumbai
plugins:
  - pollingLive:
      defaultInterval: 3000

documents:
  - ./documents/getQuiz.graphql
```

#### Document

```
query GetQuiz($id: String) @live(interval: 3000) {
  quiz(id: $id) {
    ..... query 
  }
}
```

Any ideas on the inconsistent build & error produced?

**Comment by ardatan** [comment]
It seems your document is invalid. Could you run the same command with `DEBUG=1` env var?

**Comment by GundamDweeb** [comment]
I have run it with Debug, and the error was clearly shown thank you. The `($id : String)` needed to be `($id : ID!)`.

This still doesn't solve why it worked initially without showing this error, and now it is producing it.
