### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by itsjerryokolo** [graphprotocol/graph-client#222]
I'm having this issue running graph-build after upgrading the `client-cli` to `2.2.4`
I'm using this build command for cjs: `graphclient build --fileType json`

<img width="1325" alt="Screenshot 2022-09-04 at 4 05 22 PM" src="https://user-images.githubusercontent.com/73024324/188320693-97302f34-3f35-405f-b310-87813409870b.png">

When I upgraded the cli, it showed the warnings below
<img width="1299" alt="Screenshot 2022-09-04 at 4 03 03 PM" src="https://user-images.githubusercontent.com/73024324/188320729-1555ac22-afd4-4448-8041-5b4f1549fd2f.png">

I added the dependencies, but it didn't solve the TypeError when I run the build command.
<img width="388" alt="Screenshot 2022-09-04 at 4 16 25 PM" src="https://user-images.githubusercontent.com/73024324/188320774-1522d537-c65f-4163-9e88-8244f80a931d.png">

**Comment by ardatan** [comment]
Which version of Node do you have?

**Comment by itsjerryokolo** [comment]
`v16.6.1`

**Comment by ardatan** [comment]
Could you share a minimal reproduction on CodeSandbox or StackBlitz?

**Comment by itsjerryokolo** [comment]
It works on this site. Guess this issue is unique to me. Any ideas where to look?

https://codesandbox.io/p/github/itsjerryokolo/The-Graph-Client_NodeJS/client-cli-2.2.4?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A22%2C%22endLineNumber%22%3A3%2C%22startColumn%22%3A22%2C%22startLineNumber%22%3A3%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl7nqgihs0001lmev4eak9m55%2522%252C%2522openFiles%2522%253A%255B%2522%252Fpackage.json%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522cl7nqood000um3b6f4ujivbj8%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522codegen%2522%252C%2522key%2522%253A%2522cl7nqm9pw00773b6f8zvj4dss%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

**Comment by itsjerryokolo** [comment]
Resolved. Upgrading Node to version `16.17.0` solved this issue.
Thanks @ardatan
