### ISSUE TITLE
Latest graph client (2.2.4) is importing @graphql-mesh/graphql 5 times in generated SDK

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#223]
Updated to 2.2.4 and started seeing errors about multiple imports. Checked the generated SDK and saw this...

![Screenshot_28](https://user-images.githubusercontent.com/6063350/188506575-80092931-af6b-4630-a9c8-379b59d0d503.png)

**Comment by ardatan** [comment]
Fixed and released!

**Comment by matthewlilley** [comment]
@ardatan I tried quickly updating to 2.2.5 and appeared to have the same issue, but I'll double check in the morning to be sure.
