### ISSUE TITLE
Bad assumption that schema BigInt should be transformed into JS native bigint

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#243]
There is a bad assumption is that because a property is defined as BigInt in schema, it should be parsed as native JS bigint on client. 

It makes the assumption that every single subgraph in existence is using the perfect types for all properties, but that isn't the case, often they're set to BigInt in schema just for conviniance with arithmatic in graph mapping. 

An example would be ERC20 decimals, these are unsigned 8 bit integer but everybody uses BigInt for conviniance within subgraph mappings.

**Comment by ardatan** [comment]
Reverted in the latest release.

**Comment by matthewlilley** [comment]
@ardatan I think having the ability to transform schema into native types like bigint, or class transformation is great, but a level of control is needed for legacy reasons. Some subgraphs take 6 months to complete a resync even if we wanted to make schema match, so it's impossible to do this in a short time frame, and for our use case we represent in our own value objects, so native bigint isn't useful for us currently.

**Comment by matthewlilley** [comment]
Something which functioned like this would be pretty awesome:

https://github.com/typestack/class-transformer
