### ISSUE TITLE
Enable code checks for pull requests

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#249]
I notice you added a CI workflow at some point to run build, test, etc... However it seems that whenever a new PR is opened these aren't being forced to run and pass before merge. 

It would be a good idea to enable this, we can help write some further tests so that we don't see regressions in future.

**Comment by ardatan** [comment]
CI works on each pull request. The following changeset commit makes it look like that, but that's another issue.
See https://github.com/graphprotocol/graph-client/pull/246

**Comment by matthewlilley** [comment]
@ardatan Ah, maybe something is missing. A few of these examples on the latest version should definitely cause build errors like I'm seeing with this one.

https://github.com/graphprotocol/graph-client/issues/248

**Comment by ardatan** [comment]
@matthewlilley It is a missing test for your use case in GraphQL Mesh repository. I am closing this issue and let's track there.
