### ISSUE TITLE
"Cannot find module" error due to missing runtime dependency in generated file

### ISSUE THREAD

**Issue by stefan-girlich** [graphprotocol/graph-client#254]
### context and steps to reproduce
i want to use `graph-client` in a web service, so i...

1. follow instructions on https://thegraph.com/docs/en/querying/querying-from-an-application/#graph-client for basic setup: add dev dependency, add `.graphclientrc.yml`
2. run `graphclient build`
3. reference generated code in `.graphclient/` in application code, e.g. `execute`
4. run application locally **=> success**
5. deploy application to external system which requires fresh production build =>  **runtime error** 

### status quo
- `Cannot find module '@graphql-mesh/utils'` in generated `/app/dist/.graphclient/index.js`

### expected
- generated file `/app/dist/.graphclient/index.js` has correct runtime dependencies
- docs mention how to install peer deps as runtime deps, e.g. `npx install-peerdeps -Y @graphprotocol/client-cli`

**Comment by stefan-girlich** [comment]
### workaround
1. install all `graph-client`-related peer deps manually
2. install all deps seen among generated `.graphclient/index.js` imports

please try step #2 first since step #1 may not be relevant

### example
```
yarn add @graphql-tools/delegate @graphql-tools/wrap @graphql-tools/utils @graphql-mesh/types @graphql-mesh/types @graphql-mesh/types @graphql-tools/delegate @graphql-tools/merge @envelop/core graphql-tag @graphql-mesh/cache-localforage @whatwg-node/fetch @graphql-mesh/graphql @graphql-mesh/merger-bare @graphql-mesh/http @graphql-mesh/runtime @graphql-mesh/store @graphql-mesh/cross-helpers @graphql-mesh/types
```

### concerns
- not documented in https://thegraph.com/docs/en/querying/querying-from-an-application/
- huge manual effort - is there a smaller set of meta modules which should be installed as runtime deps?
- workaround approach may break when generated `index.js` refers to new imports

**Comment by ardatan** [comment]
Please create a reproduction on CodeSandbox or StackBlitz. Thanks!
