### ISSUE TITLE
CJS build isn't consumable

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#309]
I created a minimal reproduction to demonstrate the issue with a CJS build and consuming it.

https://github.com/matthewlilley/graphclient-cjs

![Screenshot_86](https://user-images.githubusercontent.com/6063350/198150901-f0900570-a9f0-4ded-bc02-8d95b15d3b19.png)

**Comment by ardatan** [comment]
Have you tried the same query on the actual GraphQL API?

**Comment by matthewlilley** [comment]
@ardatan Yes. If you run pnpm dev and run it on the local graphql server it will work. It does this when you build CJS and try to consume it. ESM builds fail completely too.

**Comment by ardatan** [comment]
@matthewlilley I mean did you try the same query on `https://api.thegraph.com/subgraphs/name/sushiswap/exchange`?

**Comment by matthewlilley** [comment]
@ardatan The exact query is using prefix and autopagination, but a vanilla version can be seen working here:

https://thegraph.com/hosted-service/subgraph/sushiswap/exchange

**Comment by matthewlilley** [comment]
@ardatan Ah, so this shows when "first" > 1000, and "first" is passed through the SDK.

![Screenshot_87](https://user-images.githubusercontent.com/6063350/198161023-9f2f71ca-b438-44ad-a23f-e7474fd77e4c.png)

If I set $first = 1001 in the query itself, I see the full error message "The `first` argument must be between 0 and 1000, but is 1001"

![Screenshot_88](https://user-images.githubusercontent.com/6063350/198161162-4233a482-7658-46dc-a8e2-fce7ebfdbb84.png)

**Comment by matthewlilley** [comment]
@ardatan this brings me back to the original issue, which is that pagination doesn't work when you build with:

graphclient build --fileType json

and when you do graphclient build --fileType js, it fails completely

**Comment by matthewlilley** [comment]
@ardatan I did a little more digging and think I found the cause. If you don't explicitly set skip: 0 when using the SDK, it will fail to trigger autopagination. I updated the repro I shared earlier to demonstrate.

![Screenshot_90](https://user-images.githubusercontent.com/6063350/198181269-3abad416-f90a-4996-8fe5-29868f15cdb0.png)

**Comment by matthewlilley** [comment]
I've created seperate issues for the two new discoveries here and will close this for now
