### ISSUE TITLE
Different sources based on chainId

### ISSUE THREAD

**Issue by nezouse** [graphprotocol/graph-client#31]
Hi, is there a way to change source urls in runtime? Either automatically or by providing a variable is fine. 
Multiple clients is also fine i guess?
But for sure need an option to do that.

Sorry if it's obvious, but just found it and try to check if we can use it.

**Comment by azf20** [comment]
From the issue title, it seems like the motivating use case might be connecting to subgraphs for different chainIds (which presumably all have the same schema?) I wonder if this cross-chain specific issue is maybe relevant here @nezouse? https://github.com/graphprotocol/graph-client/issues/41

**Comment by nezouse** [comment]
Sorry, i totally forgot about this question. One use case is fetching cross chain and this is fine.
The other use case i was asking here for is fetching data from different subgraph based on which chain user is connected to.

Right now we have smth like this (no graph-client):
```js
const chainId = useChainId()
const getApolloLink = (chainId: ChainId) =>
  new ApolloLink((operation) => {
    const subgraph = operation.getContext().subgraph as Subgraphs
    const uri = SUBGRAPH_URLS[subgraph][chainId]
    const link = new HttpLink({ uri, fetch })
    return link.request(operation)
  })

export const SUBGRAPH_URLS = {
  [Subgraphs.A]: {
    [ChainId.Mainnet]: ',
    [ChainId.Ropsten]: '',
    [ChainId.Localhost]: '',
  },
  [Subgraphs.B]: {
    [ChainId.Ropsten]: '',
    [ChainId.Localhost]: '',
  },
}
```

**Comment by dotansimha** [comment]
Thanks, @nezouse @azf20 
Let's track this in https://github.com/graphprotocol/graph-client/issues/41
