### ISSUE TITLE
Allow setting of makeResolverTypeCallable

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-client#314]
I'm re-writing our graph-client package at the moment and run into an issue when modularising, and especially reusing resolvers.

This expression is not callable.
  Not all constituents of type 'Resolver<ResolverTypeWrapper<LiquidityPosition>[], {}, FarmTypes.Context & MasterChefV2Types.Context & BlocksTypes.Context & MasterChefV1Types.Context & XSushiTypes.Context & ... 6 more ... & { ...; }, RequireFields<...>>' are callable.

I then found this comment from @dotansimha on an old issue.

https://github.com/dotansimha/graphql-code-generator/issues/6310#issuecomment-932939901

It sounds like I want this to be enabled?

**Comment by matthewlilley** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/6063350/198821915-feb74e08-7a9f-41a1-9807-2305f20d3f83.png)

Or should it be avoided? I notice that selections aren't made if calling the resolver.

**Comment by ardatan** [comment]
You should avoid calling resolvers directly, and SDK needs to be used.

**Comment by matthewlilley** [comment]
@ardatan Thanks for clarification.

**Comment by ardatan** [comment]
Also resolvers are not always functions, they can be an object like 
```
{
  selectionSet: ...,
  resolve: (root, args, context, info) => {}
}
```

**Comment by matthewlilley** [comment]
@ardatan gotcha, have been digging into graphql, mesh & graphclient a lot over the past week. Hopefully will be able to contribute back a bit more now I'm understanding a bit more, I notice the graphclient is mostly a thin wrapper.

**Comment by matthewlilley** [comment]
@ardatan I'm still having a few problems with this.

I have a JSON handler in our config, but calling it directly inside another resolver, such as:

const farms: Query['farms'] = await context.Farm.Query.farms({ root, args, context, info })

Selections aren't made... And it's not being exposed on the SDK, so I can't use it from there either.

**Comment by matthewlilley** [comment]
@ardatan I am using sdk within some resolvers now, instead of other resolvers directly from resolvers themselves. However, I'm struggling with type errors, the SDK return type doesn't seem to be compatible with the resolver return type without casting to it.

![Screenshot_21](https://user-images.githubusercontent.com/6063350/199073463-1ae12200-bf6b-4ccd-b743-af42cafc2d36.png)

What's the best practice here? I'm always a bit hessitant about casting.

**Comment by ardatan** [comment]
Oh in resolvers, incontext sdk`context.SOURCE_NAME.Query.FIELD_NAME` should be used not the other sdk :) 
Other SDK is for clients not stitching.

**Comment by matthewlilley** [comment]
> Oh in resolvers, incontext sdk`context.SOURCE_NAME.Query.FIELD_NAME` should be used not the other sdk :) Other SDK is for clients not stitching.

Ah, so this is exactly what I was doing before. The issue then was that selections weren't made in a lot of cases. Like here:

https://github.com/graphprotocol/graph-client/issues/314#issuecomment-1295771712

**Comment by matthewlilley** [comment]
@ardatan I have situations where I want to reuse resolver logic in other resolvers, or even multiple times within the same resolver.

https://github.com/sushiswap/sushiswap/blob/refactor/graph-client/packages/graph-client-2/resolvers/pairs/index.ts#L62

Writing small wrappers is a better pattern here?

**Comment by matthewlilley** [comment]
Friendly bump on above message @ardatan. It's not clear how to deal with complex cases like this.

**Comment by matthewlilley** [comment]
I guess I should ask a few questions which would help.

Are there cases where it's acceptable to use the SDK within a resolver?

If not, and we want to reuse logic which is used in custom resolvers, what is the best practice for this? 

An example of such as case can be seen here:
https://github.com/sushiswap/sushiswap/blob/refactor/graph-client/packages/graph-client-2/resolvers/pairs/index.ts#L62

Here we cannot use "context.SOURCE_NAME.Query.FIELD_NAME" since the query is an extension and isn't available here, the query might be shared by multiple contexts too.
