### ISSUE TITLE
Invalid Regular Expression via itty-router

### ISSUE THREAD

**Issue by TheDojoSamurai** [graphprotocol/graph-client#326]
I am getting this error, only when running the Graph-client in a mobile browsers.

Any idea on how to solve this?

![2022-11-01 at 11 59 AM](https://user-images.githubusercontent.com/83392401/199162448-1aee9cc5-e9ef-44b3-b6a1-1b1dbc4b9f70.jpg)

Posted on `itty-router` as well: https://github.com/kwhitley/itty-router/issues/124

**Comment by TheDojoSamurai** [comment]
Anyone? this actually makes my ReactApp crash on mobile.

**Comment by ardatan** [comment]
`itty-router` is used only if you use http handler in your app but I don't think you use it on a FE app. So is it possible to share a reproduction?

**Comment by TheDojoSamurai** [comment]
My app is setup based on the [urql-live-query example](https://github.com/graphprotocol/graph-client/tree/main/examples/urql-live-query)


In my App.tsx

```
import { createClient, Provider } from 'urql'
import * as GraphClient from './graphclient'
import { graphExchange } from '@graphprotocol/client-urql'

const client = createClient({
  url: http://127.0.0.1:8000/subgraphs/name/local-test-graph,
  exchanges: [graphExchange(GraphClient)],
})

```

Example query call:

```

const GetUserTokens = `
  query GetUserTokens($accountAddress: String!) 
    @live(interval: 20000) {
      account(id: $accountAddress) {
      nftTokens {
        id
        token
        tokenId
      }
    }
  }
`

const [result, reexecuteQuery] = useQuery({
  query: GetUserTokens,
    variables: {
      accountAddress: address
    },
})
```

**Comment by n1ru4l** [comment]
> I am getting this error, only when running the Graph-client in a mobile browsers.

Can you please specify the browser and browser version?

**Comment by frankfka** [comment]
We're getting this as well - with Next.js, this actually causes all interactivity / JS to fail.

**Comment by hash0000FF** [comment]
I am facing the same issue in mobile/desktop safari. I solved this by downgrading the package based on @frankfka's finding. And it works again.

```
    "@graphprotocol/client-cli": "2.2.10",

```

**Comment by dotansimha** [comment]
@ardatan can you please check if it's relevant with the latest version?

**Comment by ardatan** [comment]
We no longer use itty-router. So this shouldn't exist anymore.
