### ISSUE TITLE
`any` in Scalars output for Bytes, BigInt, BigDecimal

### ISSUE THREAD

**Issue by kasparkallas** [graphprotocol/graph-client#329]
I ran the examples and got `any` for Bytes, BigInt, BigDecimal in the Scalars. Is this normal? I'd prefer my scalar value to be unambiguous and clearly serializable/deserializable. 

Before using `graph-client`, I generated the output myself using `graphql-code-generator` and set the output for these types as `string` which worked well. Is it possible as a user of `graphql-client` to tweak the internal code generator config to set different values to the scalars? And possibly tweak other aspects of the output as well.

**Comment by ardatan** [comment]
Yes you can configure codegen like below;
```yml
codegen:
  scalars:
    BigInt: string
    Bytes: string
    BigDecimal: string
```
Also you can see the discussion here why we don't set anything for those by default;
https://github.com/graphprotocol/graph-client/issues/90

**Comment by kasparkallas** [comment]
@ardatan Love it, will work great for me, thanks!

**Comment by froid1911** [comment]
any chance, that we can transform a bigint to a BigInt, BigDecimal to BigDecimal etc?
