### ISSUE TITLE
all dependencies should use caret (`^`) ranges

### ISSUE THREAD

**Issue by n1ru4l** [graphprotocol/graph-client#334]
Right now, a few of the packages use pinned versions.

**Comment by ardatan** [comment]
I remember `^` doesn't work much for `0.x` versions. I think we aren't going to be able to do that until Mesh v1.

**Comment by n1ru4l** [comment]
@ardatan Not sure what you mean in the `0.X.X` range the second number acts as the major version.



so a constraint of `^0.100.2` would satisfy `0.100.2`, `0.100.3`, `0.100.n` BUT NOT satisfy `0.101.n`.

https://jubianchi.github.io/semver-check/#/^0.100.2/0.100.2
https://jubianchi.github.io/semver-check/#/^0.100.2/0.100.3
https://jubianchi.github.io/semver-check/#/^0.100.2/0.101.99
https://jubianchi.github.io/semver-check/#/^0.100.2/0.101.2

**Comment by ardatan** [comment]
Closed by https://github.com/graphprotocol/graph-client/pull/435
