### ISSUE TITLE
Option to stop polling/querying if tab is not active

### ISSUE THREAD

**Issue by schmidsi** [graphprotocol/graph-client#354]
A smart and sophisticated way pioneered by Premia to reduce requests and save query fees on The Graph Network is to only send queries as long as the tab/window/document is active or visible. They created a custom Apollo Middleware but I think this could be solved directly in Graph Client.

https://developer.mozilla.org/en-US/docs/Web/API/Document/hidden#browser_compatibility

**Comment by ardatan** [comment]
I just created this WIP PR. You can test with the canaries;
https://github.com/graphprotocol/graph-client/pull/355#issuecomment-1377396543
