### ISSUE TITLE
Install doesn't work

### ISSUE THREAD

**Issue by simundev** [graphprotocol/graph-client#361]
As per instructions I have run:

```
npm install --save-dev @graphprotocol/client-cli
```

It worked, but then running:

```
graphclient build
```

Results in error:

```
graphclient not found
```

Mac OS X, zsh.

**Comment by dotansimha** [comment]
Hi @simundev ,
If you are using `npm` and does not install deps globally, you will not be able to run the CLI as-is. 
With Yarn or `pnpm`, you can do `yarn graphclient build` or `pnpm graphclient build`. With `pnpm`, you can workaround this by adding a script to your `package.json` and just call it:

```json
"scripts": {
  "build": "graphclient build"
}
```

```
npm run build
```

**Comment by simundev** [comment]
Hi @dotansimha , thanks for the quick reply.

This is the repo I have cloned:
https://github.com/graphprotocol/graph-client/tree/main/examples/javascript-cjs

I have run `yarn` to install dependencies. However neither `yarn graphclient build` nor `npm graphclient build` work. They can't see/find `graphclient`. I also can't see it anywhere, `which graphclient` does not return a location.

As mentioned, I have run 

`npm install --save-dev @graphprotocol/client-cli`

My `node_modules` in the graph-client root directory contains the `@graphprotocol` folder. But I can't locate `graphclient` script or binary anywhere on my system, so I am not surprised I can't run it either.

Any help here is greatly appreciated.

**Comment by dotansimha** [comment]
@ardatan can you please take a look?

**Comment by ardatan** [comment]
As @dotansimha already mentioned earlier, `which` command won't work because `graphclient` is not installed globally on your system. This is not issue.
`npm graphclient` won't work because if you install the stuff there with `npm`, you have to use `npx graphclient` not `npm`.
If you install dependencies with `yarn`, `yarn` prefix can be used instead of `npx`.
If these still don't work for you, could you create a sandbox on CodeSandbox or StackBlitz with the code exactly what you're trying to do. Thanks!

**Comment by simundev** [comment]
Thanks @ardatan 

Yarn does not work. I have now tried `npx run graphclient` and got this

```
Starting: graphclient build
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/Users/simun/Code/graph-client/examples/javascript-cjs/graphclient'
```

Could you please advise where the `graphclient` binary or script should be on the system so I can check whether it is there and this is a PATH issue on my system?

I am not trying to do something in particular, just run the example from this repo:
https://github.com/graphprotocol/graph-client/tree/main/examples/javascript-cjs

But it is as if `graphclient` is simply nowhere on my system, `yarn/npm/npx` can't see it.

**Comment by ardatan** [comment]
I think it is your configuration because it seems to be working here;
https://codesandbox.io/s/github/graphprotocol/graph-client/tree/add-codesandbox-config/examples/javascript-cjs
That's why I asked for a sandbox :)

**Comment by simundev** [comment]
Thanks @ardatan ,

I do understand that it works for other people, because when I googled the problem I could not find anything. That is also why I raised this issue. I cannot understand what I did wrong as I followed instructions to the letter, and I do have the cli installed. My configuration is not exotic, a quite vanilla Mac OS (M1).

The `graphclient` command is simply not visible to the terminal, and I don't know why... :(

**Comment by ardatan** [comment]
`graphclient` command should never be available globally as-is :)
Try copy-pasting the example in a clean directory outside of the repo, and run `yarn` then `yarn graphclient build`.

**Comment by simundev** [comment]
I tried that and it worked!

@ardatan thank you ser!

So I guess yarn/npm can not pick up / interact with the cli unless it is in the `node_modules` in the same directory?

Strange that only I experience this.

**Comment by ardatan** [comment]
I guess you used the repo so our repo is a monorepo that uses Yarn workspaces so `npm` cannot be used.
You should install the dependencies in the root of this kind of monorepos then run `build` to build the packages because other packages in a monorepo use the built version in the same monorepo.
You can check Yarn workspaces to learn more about this behavior.
