### ISSUE TITLE
Built-in pagination for making it easier to deal with `graph-node` limitations?

### ISSUE THREAD

**Issue by dotansimha** [graphprotocol/graph-client#38]
The goal of this idea is to have an option to allow users to fetch more than the limit of `graph-node`, without being concerned about orchestrating calls.

Today, the limit is 1000 records per page.

For example, if a user needs to have more than 1000 (for example 5000), they should be able to specify it in their GraphQL request, and then `graph-client` can orchestrate the 5 calls to get the list of data, and then merge it into a single response.

**Comment by dotansimha** [comment]
@ardatan let's explore this option to have an Executor that is aware of this feature? :)

**Comment by schmidsi** [comment]
Important here is that the recommended approach of paginating through a bigger data set is using the `..._gt` filters on numerical attributes like block number or timestamp. Instead of using the `first:`, `skip:` arguments.

**Comment by dotansimha** [comment]
> Important here is that the recommended approach of paginating through a bigger data set is using the `..._gt` filters on numerical attributes like block number or timestamp. Instead of using the `first:`, `skip:` arguments.

Interesting, thanks @schmidsi ! 
@ardatan do you think we can add the mode into [the new transformer](https://github.com/graphprotocol/graph-client/pull/37) ?

**Comment by dotansimha** [comment]
This is now available in `@graphprotocol/client-cli@0.0.5`, docs: https://github.com/graphprotocol/graph-client/blob/main/packages/auto-pagination/README.md
