### ISSUE TITLE
Question: query same Entity in two different sources?

### ISSUE THREAD

**Issue by cazala** [graphprotocol/graph-client#392]
If I have two exact subgraphs deployed on different chains, is it possible to query a single entity that returns a list of results from both sources?

The two sources have the same schema for the Entity, but the records don't share a unique identifier.

For examle, I have an entity Token on both subgraphs:

```gql
type Token @entity {
  id: ID! #address
  name: String
}
```

And this query when executed on each subgraph:

```gql
query {
  tokens {
    id
    name
  }
}
```

Return the following on the Ethereum subgraph:

```json
{
  "tokens": [
    {
      "id": "0x1",
      "name": "FOO"
    }
  ]
}
```

And this on the Polygon one:

```json
{
  "tokens": [
    {
      "id": "0x2",
      "name": "BAR"
    }
  ]
}
```

And I want to be able to run that same query and get this result:

```json
{
  "tokens": [
    {
      "id": "0x1",
      "name": "FOO"
    },
    {
      "id": "0x2",
      "name": "BAR"
    }
  ]
}
```

And be able to apply sorting/filtering on top of it. Is that possible with the current state of the `graph-client`?

**Comment by cazala** [comment]
I tried this already using some of our Ethereum/Polygon subgraphs but I'm only getting results from the first source and the other one is completely ignored. If I comment the first one then I start getting the results from the other. I don't know if I'm missing some configuration to tell the graph mesh to treat both entities as the same (even tho they are already called the same).

**Comment by dotansimha** [comment]
It sounds like the cross-chain feature (see https://github.com/graphprotocol/graph-client/tree/main/examples/cross-chain-sdk), but with different sources? 
I mean, it is possible to merge responses easily with Graph Client, and it is possible to orchestrate calls to 2 different Subgraphs, so I think it might be possible with some adjustments. 
@ardatan what do you think?

**Comment by ardatan** [comment]
You can overwrite `tokens` in an additional resolvers;
```ts
export const resolvers: Resolvers = {
   Query: {
      async tokens(root, args, context, info) {
         const tokensNonFlat = await Promise.all([
           context.Ethereum.Query.tokens({ root, args, context, info }),
           context.Polygon.Query.tokens({ root, args, context, info })
         ]);
         return tokenNonFlat.flat();
      }
   }
}
```

**Comment by cazala** [comment]
> You can overwrite `tokens` as an additional resolver;
> 
> ```ts
> export const resolvers: Resolvers = {
>    Query: {
>       async tokens(root, args, context, info) {
>          const tokensNonFlat = await Promise.all([
>            context.Ethereum.Query.tokens({ root, args, context, info }),
>            context.Polygon.Query.tokens({ root, args, context, info })
>          ]);
>          return tokenNonFlat.flat();
>       }
>    }
> }
> ```

Would that work for sorting/pagintation tho? Or would the results be ordered as `[...ethereum, ...polygon]`? Sorting/filtering/pagination of the results is key for our use case.

For example, if I'm fetching NFTs in a marketplace and sorting the results by price, and the Ethereum ones are an order of magnitude more expensive than the Polygon ones, if the results are always `[...ethereum, ...polygon]` even if I `orderBy: price` I will always see the Ethereum results in the first page even tho the Polygon results should show up first.

**Comment by ardatan** [comment]
```ts
const [ethResults, polygonResults] = await Promise.all([
           context.Ethereum.Query.tokens({ root, args, context, info }),
           context.Polygon.Query.tokens({ root, args, context, info })
         ]);
         return [...ethResults, ...polygonResults];
      }
```
You can do this to change priority (it is just JavaScript, nothing with Graph Client).
I don't think Graph Client can handle the pagination in total results but send the same arguments to them.
@dotansimha

**Comment by dotansimha** [comment]
> You can do this to change priority (it is just JavaScript, nothing with Graph Client). I don't think Graph Client can handle the pagination in total results but send the same arguments to them. @dotansimha

Yeah, I agree that this is a tricky one to handle with a magic config...
