### ISSUE TITLE
Leverage `extensions` in `graph-node` responses

### ISSUE THREAD

**Issue by dotansimha** [graphprotocol/graph-client#4]
This is an open issue to discuss the option to add some metadata in `graph-node` responses, using the `extensions` field of GraphQL response.

**Comment by dotansimha** [comment]
@lutter @azf20 what do you think about this? 

We discussed this with several daaps developers, we think maybe the gateway/graph-node can have an option to return execution/cost/indexing information, and we can have an easy API/tooling on The Graph client to use those (for deciding on preferred indexer/source, collecting some metrics, finding performance bottlenecks and so on)

**Comment by azf20** [comment]
That makes sense to me - @Jannis what do you think?

There is some corresponding work in `graph-node`, and maybe also in Gateways to support? Of course would also need to decide what metadata is of interest etc.

**Comment by ardatan** [comment]
This is available via `includeHttpDetailsInExtensions` flag. @dotansimha

**Comment by dotansimha** [comment]
Thanks @ardatan ! Closing ;)
