### ISSUE TITLE
Sveltekit integration

### ISSUE THREAD

**Issue by Valentin-Seehausen** [graphprotocol/graph-client#426]
Hey guys,

I tried several things and combinations, also with predefined queries to use type-safety.

Ultimately, I think it all boils down, that this CLI library does not really work with  `"type": "module"`. I have to remove this from my package.json, so it builds, but then in the end, when I build with `--fileType js` I get this error:

`Internal server error: Failed to resolve entry for package "/path/.graphclient". The package may have incorrect main/module/exports specified in its package.json.`

It would be awesome if this could work because your features are great. 

Let me know if you need any help.

**Comment by ardatan** [comment]
Please share a reproduction on CodeSandbox or StackBlitz. Thanks!

**Comment by Valentin-Seehausen** [comment]
I already did here: https://github.com/graphprotocol/graph-client/issues/409

Let me know if you need help reproducing it. 

If you are able to guide how to integrate the @live feature in a svelte project, it would also of great help! :-)

**Comment by ardatan** [comment]
Could you remove `package.json` under `.graphclient` and move `.graphclient` under `src` and try again?

**Comment by ardatan** [comment]
Closing due to the lack of response. We can reopen it after your response if the issue remains.
