### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by alxlacayo** [graphprotocol/graph-client#480]
I followed the instructions here: https://thegraph.com/docs/en/querying/querying-from-an-application/#graph-client to query the graph from a react application. I am successfully retrieving data however in the console I am getting the following error: 

`/node_modules/@graphql-mesh/utils/esm/defaultImportFn.js
Critical dependency: the request of a dependency is an expression`

Anyone know the solution?

**Comment by ardatan** [comment]
See;
https://github.com/graphprotocol/graph-client/issues/303

**Comment by alxlacayo** [comment]
> 

Thank you. I've ignored the warning via webpack config.

**Comment by pugbyte** [comment]
Hey @alxlacayo, how did you configure Webpack to ignore this warning?
