### ISSUE TITLE
Faced with memory leaks when work with autoPagination + pollingLive 

### ISSUE THREAD

**Issue by alohamonius** [graphprotocol/graph-client#483]
Hello community, I hope you can guide me to the solution.
So I work with dexes to fetch information about ALL pairs/pools. I use pollingLive with auto pagination plugins for graph clients.  As a result, my usedHeap increased on 10Mb/s and I got out of memory exception, or every fetch increase the heap on the 100MB. I have commented all my code and only left graph clients, and have the same problem.

So I have few questions about:
1. Can I clear data inside mesh?
2. For now I using one MeshInstance per dex(v2,v3), with Repeater object going through all results. Maybe I did wrong here?

```
 "@graphprotocol/client-cli": "^2.2.21",
 "@graphprotocol/client-polling-live": "1.1.1",
 "graphql": "16.6.0",
```

**Comment by ardatan** [comment]
Could you create an example repo for us to reproduce the leak?

**Comment by alohamonius** [comment]
https://github.com/alohamonius/graph-memory-leak

**Comment by ardatan** [comment]
One thing I noticed in my first look.
These are internal functions;
https://github.com/alohamonius/graph-memory-leak/blob/master/index.ts#L20
We don't recommend to use them in production. You should use the instance from `.graphclient` (artifacts).

**Comment by alohamonius** [comment]
I added [version2 without parseConfig](https://github.com/alohamonius/graph-memory-leak/blob/master/index2.ts).
The same behavior, 
3:56:05 PM heapUsed  │ 353.22 
4:03:55 PM heapUsed  │ 533.65

**Comment by alohamonius** [comment]
@ardatan Did you check v2 without internal method?
So what I can do? Can I somehow clean the data inside?

**Comment by ardatan** [comment]
@alohamonius Why did you reopen it?

**Comment by alohamonius** [comment]
> @alohamonius Why did you reopen it?
Hello. Because of something really strange with live polling. App eats memory for one hour up to 4GB. But when I use 'execute' with cron-job results are much better. But no problem, I will close again. Thanks)
