### ISSUE TITLE
CLI exits with 0 even when graph deploy has failed

### ISSUE THREAD

**Issue by jaybuidl** [graphprotocol/graph-client#608]
## Package
@graphprotocol/graph-cli@0.64.0

## Expected behaviour
If `graph deploy` fails, it should exit with 1, so that the error can be reported or handled in a CI context (e.g. Github workflow)

## Actual behaviour
If `graph deploy` fails, it should exit with 0.

## Steps to reproduce
1. Run `graph deploy --studio -l existingLabel` 
2. Run `echo $?`

![image](https://github.com/graphprotocol/graph-client/assets/22213980/06a0ee07-5cad-47af-a183-c922e08a4bc6)

**Comment by ardatan** [comment]
Are you looking for graph-cli? Because this repo belongs to graph-client.

**Comment by jaybuidl** [comment]
Indeed! Just noticed that this is @graphprotocol/client-cli not @graphprotocol/cli. My bad!

**Comment by jaybuidl** [comment]
Found it 🙌    https://github.com/graphprotocol/graph-tooling/tree/main/packages/cli
