### ISSUE TITLE
Cannot install graphprotocol/client-cli

### ISSUE THREAD

**Issue by kydchen** [graphprotocol/graph-client#610]
No matter these two ways were failed:

npm install --save-dev @graphprotocol/client-cli
info: please complete authentication in your browser...ROOT chalk@3.0.0 OK for: @graphprotocol/graph-cli@0.33.1 want: 3
info: please complete authentication in your browser...ROOT chalk@3.0.0 OK for: @graphprotocol/graph-cli@0.33.1 want: 3
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/hugomrdias/concat-stream.git
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/hugomrdias/concat-stream.git/' not found
------------------------------

yarn add -D @graphprotocol/client-cli
yarn add v1.22.21
info No lockfile found.
[1/4] Resolving packages...
warning @goldskycom/cli > cuid@2.1.8: Cuid and other k-sortable and non-cryptographic ids (Ulid, ObjectId, KSUID, all UUIDs) are all insecure. Use @paralleldrive/cuid2 instead.
warning @graphprotocol/graph-cli > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @graphprotocol/graph-cli > ipfs-http-client@34.0.0: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
warning @graphprotocol/graph-cli > request > har-validator@5.1.5: this library is no longer supported
warning @graphprotocol/graph-cli > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @graphprotocol/graph-cli > ipfs-http-client > cids@0.7.5: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-raw@4.0.1: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-raw > cids@0.7.5: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipfs-block > cids@0.7.5: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-cbor@0.15.3: This module has been superseded by @ipld/dag-cbor and multiformats
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-cbor > cids@0.8.3: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > is-ipfs > cids@0.7.5: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-pb@0.17.4: This module has been superseded by @ipld/dag-pb and multiformats
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-pb > cids@0.7.5: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > multiaddr@6.1.1: This module is deprecated, please upgrade to @multiformats/multiaddr
warning @graphprotocol/graph-cli > ipfs-http-client > is-ipfs > multiaddr@7.5.0: This module is deprecated, please upgrade to @multiformats/multiaddr
warning @graphprotocol/graph-cli > ipfs-http-client > is-ipfs > multiaddr > cids@0.8.3: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > multicodec@0.5.7: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > cids > multicodec@1.0.4: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-raw > multicodec@1.0.4: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-cbor > multicodec@1.0.4: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-cbor > cids > multicodec@1.0.4: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-pb > multicodec@0.5.7: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > promisify-es6@1.0.3: Unmaintained
warning @graphprotocol/graph-cli > ipfs-http-client > multibase@0.6.1: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > cids > multibase@0.6.1: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-cbor > cids > multibase@1.0.1: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > is-ipfs > multibase@0.6.1: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > is-ipfs > multiaddr > multibase@0.7.0: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > multihashes > multibase@0.7.0: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-cbor > cids > multihashes > multibase@1.0.1: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > peer-info@0.15.1: No longer supported for js-libp2p0.28.0 or later
warning @graphprotocol/graph-cli > ipfs-http-client > peer-info > multiaddr@6.1.1: This module is deprecated, please upgrade to @multiformats/multiaddr
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-pb > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-raw > multihashing-async@0.8.2: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-cbor > multihashing-async@0.8.2: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-pb > multihashing-async@0.7.0: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > is-ipfs > mafmt > multiaddr@7.5.0: This module is deprecated, please upgrade to @multiformats/multiaddr
warning @graphprotocol/graph-cli > ipfs-http-client > peer-info > mafmt > multiaddr@6.1.1: This module is deprecated, please upgrade to @multiformats/multiaddr
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-pb > protons@1.2.1: This module is no longer maintained
warning @graphprotocol/graph-cli > ipfs-http-client > peer-id > libp2p-crypto > multihashing-async@0.5.2: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > peer-id > libp2p-crypto > protons@1.2.1: This module is no longer maintained
⠂ sha.js@^2.4.0info: please complete authentication in your browser...
warning @graphprotocol/graph-cli > ipfs-http-client > peer-id > libp2p-crypto > libp2p-crypto-secp256k1@0.3.1: Included in libp2p-crypto, use it instead. https://github.com/libp2p/js-libp2p-crypto
warning @graphprotocol/graph-cli > ipfs-http-client > peer-id > libp2p-crypto > libp2p-crypto-secp256k1 > multihashing-async@0.6.0: This module has been superseded by the multiformats module
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/hugomrdias/concat-stream.git
Directory: C:\...\polymarket-subgraph
Output:
remote: Repository not found.
fatal: repository 'https://github.com/hugomrdias/concat-stream.git/' not found

**Comment by saihaj** [comment]
what version are you installing? do you have Graph CLI installed too? seems like this error is from Graph CLI

**Comment by passer-byzhang** [comment]
Hi saihaj,How did you solve this?
