### ISSUE TITLE
"an identifier or keyword cannot immediately follow a numeric literal"

### ISSUE THREAD

**Issue by gigamesh** [graphprotocol/graph-client#649]
When I `graphclient build`, this happens in the generated `.graphclient/index.ts` file:

![image](https://github.com/graphprotocol/graph-client/assets/32403632/81eeea9f-d4a9-4be8-97da-78e07931f879)

Is there a way to prevent it? I'm currently manually fixing it every time.

**Comment by ardatan** [comment]
This has been fixed in the latest version. 
https://github.com/graphprotocol/graph-client/pull/650
Could you confirm? Thanks!

**Comment by ardatan** [comment]
This should be fixed in the latest release. Could you update and try again?

**Comment by gigamesh** [comment]
Beautiful. thanks! 
![image](https://github.com/graphprotocol/graph-client/assets/32403632/acc28b07-1bcf-437f-8642-128b29eb4fde)
